# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: prismify.portfolio::lang.controllers.projects.config.form.name

# Model Form Field configuration
form: $/prismify/portfolio/models/project/fields.yaml

# Model Class name
modelClass: Prismify\Portfolio\Models\Project

# Default redirect location
defaultRedirect: prismify/portfolio/projects

# Create page
create:
    title: prismify.portfolio::lang.controllers.projects.config.form.create.title
    redirect: prismify/portfolio/projects/update/:id
    redirectClose: prismify/portfolio/projects

# Update page
update:
    title: prismify.portfolio::lang.controllers.projects.config.form.update.title
    redirect: prismify/portfolio/projects
    redirectClose: prismify/portfolio/projects

# Preview page
preview:
    title: prismify.portfolio::lang.controllers.projects.config.form.preview.title
